-- API: GET /noise/measure/info
SELECT T1.NMS_NM AS "name",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '01' AND T2.NMT_NO = T1.NMT_NO) AS "month1",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '02' AND T2.NMT_NO = T1.NMT_NO) AS "month2",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '03' AND T2.NMT_NO = T1.NMT_NO) AS "month3",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '04' AND T2.NMT_NO = T1.NMT_NO) AS "month4",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '05' AND T2.NMT_NO = T1.NMT_NO) AS "month5",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '06' AND T2.NMT_NO = T1.NMT_NO) AS "month6",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '07' AND T2.NMT_NO = T1.NMT_NO) AS "month7",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '08' AND T2.NMT_NO = T1.NMT_NO) AS "month8",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '09' AND T2.NMT_NO = T1.NMT_NO) AS "month9",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '10' AND T2.NMT_NO = T1.NMT_NO) AS "month10",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '11' AND T2.NMT_NO = T1.NMT_NO) AS "month11",
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ?
AND SUBSTR(T2.YYYYMM,5,6) = '12' AND T2.NMT_NO = T1.NMT_NO) AS "month12",
(SELECT DISTINCT(T2.AVERAGE) FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? AND T2.NMT_NO = T1.NMT_NO) AS "average"
FROM TL_NS_MSRSTN T1
WHERE 1=1
-- [동적 조건] airportCode → AND T1.ARP_SE = ?
-- (base_param: year 가 서브쿼리 내 13개 ? 에 바인딩)
ORDER BY T1.NMT_NO