SELECT T1.NMS_NM AS NAME, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '01' AND T2.NMT_NO = T1.NMT_NO) AS MONTH1, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '02' AND T2.NMT_NO = T1.NMT_NO) AS MONTH2, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '03' AND T2.NMT_NO = T1.NMT_NO) AS MONTH3, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '04' AND T2.NMT_NO = T1.NMT_NO) AS MONTH4, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '05' AND T2.NMT_NO = T1.NMT_NO) AS MONTH5, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '06' AND T2.NMT_NO = T1.NMT_NO) AS MONTH6, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '07' AND T2.NMT_NO = T1.NMT_NO) AS MONTH7, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '08' AND T2.NMT_NO = T1.NMT_NO) AS MONTH8, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '09' AND T2.NMT_NO = T1.NMT_NO) AS MONTH9, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '10' AND T2.NMT_NO = T1.NMT_NO) AS MONTH10, 
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '11' AND T2.NMT_NO = T1.NMT_NO) AS MONTH11, +
(SELECT T2.WECPNL FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? 
AND SUBSTR(T2.YYYYMM,5,6) = '12' AND T2.NMT_NO = T1.NMT_NO) AS MONTH12, 
(SELECT DISTINCT(T2.AVERAGE) FROM T_NS_MONTH_WECP T2 WHERE T2.ARP_SE = T1.ARP_SE AND SUBSTR(T2.YYYYMM,0,4) = ? AND T2.NMT_NO = T1.NMT_NO) AS AVERAGE 
FROM TL_NS_MSRSTN T1
WHERE 1=1
-- [동적 조건] airportCode → AND T1.ARP_SE = ?
-- (base_param: year 가 서브쿼리 내 13개 ? 에 바인딩)
ORDER BY T1.NMT_NO