SELECT 
    CASE WHEN T1.IO = 'O' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT ) 
         WHEN T1.IO = 'I' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS BOARDING_KOR, 
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT) 
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS BOARDING_ENG, 
    CASE WHEN T1.IO = 'O' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  
         WHEN T1.IO = 'I' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS ARRIVED_KOR, 
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS ARRIVED_ENG, 
    T2.AIRLINE_KOREAN, 
    T2.AIRLINE_ENGLISH, 
    T2.AIRLINE_CODE2||T1.FLN AS AIR_FLN, 
    T1.STD, 
    T1.ETD, 
    T1.IO, 
    CASE WHEN T1.LINE = 'D' THEN '국내' WHEN T1.LINE = 'I' THEN '국제' END AS LINE , 
    T1.GATE, 
    T3.RMK_KOR, 
    T3.RMK_ENG, 
    T1.CITY, 
    T1.AIRPORT 
FROM 
    AIRPORT_FIDS_SCHEDULE T1 LEFT JOIN AIRPORT_AIRLINE_CODE T2 ON T1.ICAO = T2.AIRLINE_CODE3 AND T1.IATA = T2.AIRLINE_CODE2
    LEFT JOIN FIDS_STATUS T3 ON T1.RMK = T3.RMK_CODE 
WHERE T1.ACT_C_DATE = TO_CHAR(sysdate, 'yyyymmdd') AND T1.FST IN ('11', '13', '15') AND T1.PPC IN ('00', '08') AND (T1.DEL != 'Y' OR (T1.DEL='Y' AND T1.RMK='SNL'))
    
    
    
    
    
    
    
    
    
    
ORDER BY T1.STD ASC
