SELECT LINES.ARP AS ARP, 
       LINES.ODP AS ODP, 
       LINES.TOF AS TOF,
       CPAIR.C_KM AS KM,
       CPAIR.C_TIME AS TIME
  FROM (
	SELECT DISTINCT 
       		DOMESTIC_START_CITY AS ARP
	       , DOMESTIC_ARRIVAL_CITY AS ODP
	       , 'D' AS TOF
	  FROM AIRPORT_SCHEDULE_DOME AD
	 WHERE 1 = 1
                
                
      union all
	SELECT DISTINCT
	       INTERNATIONAL_AIRPORT_DOME AS ARP
	       , INTERNATIONAL_AIRPORT_INTE AS ODP
	       , 'I' AS TOF
	  FROM AIRPORT_SCHEDULE_INTE
	 WHERE 1 = 1
                
                
	   AND INTERNATIONAL_IO_TYPE = 'OUT'
      union all
	SELECT DISTINCT
	       INTERNATIONAL_AIRPORT_INTE AS ARP
	       , INTERNATIONAL_AIRPORT_DOME AS ODP
	       , 'I' AS TOF
	  FROM AIRPORT_SCHEDULE_INTE
	 WHERE 1 = 1
                
                
	   AND INTERNATIONAL_IO_TYPE = 'IN'
        ) LINES, AIRPORT_CPAIR CPAIR
 WHERE 1 = 1
   AND LINES.ARP = CPAIR.C_ORG
   AND LINES.ODP = CPAIR.C_DST
    
    
 ORDER BY ARP, KM DESC