SELECT 
    A.DOMESTIC_NUM, 
    A.DOMESTIC_START_TIME, 
    A.DOMESTIC_ARRIVAL_TIME, 
    A.DOMESTIC_MON, 
    A.DOMESTIC_TUE, 
    A.DOMESTIC_WED, 
    A.DOMESTIC_THU, 
    A.DOMESTIC_FRI, 
    A.DOMESTIC_SAT, 
    A.DOMESTIC_SUN, 
    A.DOMESTIC_STDATE,
    A.DOMESTIC_EDDATE,
    B.AIRLINE_KOREAN,
    B.AIRLINE_ENGLISH,
    B.AIRLINE_HOMEPAGE_URL, 
    A.DOMESTIC_START_CITY AS STARTCITY_CODE,
    (SELECT CITY_KOR FROM AIRPORT_CITY_CODE WHERE CITY_CODE = A.DOMESTIC_START_CITY) as STARTCITY,
    A.DOMESTIC_ARRIVAL_CITY AS ARRIVALCITY_CODE,
    (SELECT CITY_KOR FROM AIRPORT_CITY_CODE WHERE CITY_CODE = A.DOMESTIC_ARRIVAL_CITY) as ARRIVALCITY,
    CASE WHEN FST IN ('11', '13', '14', '15') THEN '여객기'
         WHEN FST IN ('21', '22', '23') THEN '화물기'
         ELSE '기타' END AS FLIGHT_PURPOSE
FROM 
    AIRPORT_SCHEDULE_DOME A, 
    AIRPORT_AIRLINE_CODE B
WHERE B.AIRLINE_CODE2=SUBSTR(A.DOMESTIC_NUM,0,2) and FST != '12' 
    
    
    
    
    
    
ORDER BY A.DOMESTIC_START_TIME ASC 