CREATE TABLE AIRPORT_PARKINGLIVE (
    PARKING_IINCNT NUMBER,
    PARKING_IOUTCNT NUMBER,
    PARKING_ISTAY NUMBER,
    PARKING_GETDATE DATE,
    PARKING_AIRPORT_CODE_NAME VARCHAR2(100),
    PARKING_PULL_SPACE NUMBER,
    PARKING_AIRPORT_CODE NUMBER
);

BEGIN
  FOR i IN 1..100 LOOP
    INSERT INTO AIRPORT_PARKINGLIVE (
      PARKING_IINCNT, PARKING_IOUTCNT, PARKING_ISTAY, PARKING_GETDATE,
      PARKING_AIRPORT_CODE_NAME, PARKING_PULL_SPACE, PARKING_AIRPORT_CODE
    ) VALUES (
      MOD(ABS(DBMS_RANDOM.RANDOM), 1000),
      MOD(ABS(DBMS_RANDOM.RANDOM), 1000),
      MOD(ABS(DBMS_RANDOM.RANDOM), 500),
      SYSDATE - DBMS_RANDOM.VALUE(0, 30),
      '주차장 ' || i,
      MOD(ABS(DBMS_RANDOM.RANDOM), 2000) + 1000,
      MOD(i, 13) + 1
    );
  END LOOP;
  COMMIT;
END;
/
EXIT;
