-- API: GET /flight/schedule/dom
SELECT 
    A.DOMESTIC_NUM, 
    A.DOMESTIC_START_TIME, 
    A.DOMESTIC_ARRIVAL_TIME, 
    A.DOMESTIC_MON, 
    A.DOMESTIC_TUE, 
    A.DOMESTIC_WED, 
    A.DOMESTIC_THU, 
    A.DOMESTIC_FRI, 
    A.DOMESTIC_SAT, 
    A.DOMESTIC_SUN, 
    A.DOMESTIC_STDATE,
    A.DOMESTIC_EDDATE,
    B.AIRLINE_KOREAN,
    B.AIRLINE_ENGLISH,
    B.AIRLINE_HOMEPAGE_URL, 
    A.DOMESTIC_START_CITY AS STARTCITY_CODE,
    (SELECT CITY_KOR FROM AIRPORT_CITY_CODE WHERE CITY_CODE = A.DOMESTIC_START_CITY) as STARTCITY,
    A.DOMESTIC_ARRIVAL_CITY AS ARRIVALCITY_CODE,
    (SELECT CITY_KOR FROM AIRPORT_CITY_CODE WHERE CITY_CODE = A.DOMESTIC_ARRIVAL_CITY) as ARRIVALCITY,
    CASE WHEN FST IN ('11', '13', '14', '15') THEN '여객기'
         WHEN FST IN ('21', '22', '23') THEN '화물기'
         ELSE '기타' END AS FLIGHT_PURPOSE
FROM 
    AIRPORT_SCHEDULE_DOME A, 
    AIRPORT_AIRLINE_CODE B
WHERE B.AIRLINE_CODE2=SUBSTR(A.DOMESTIC_NUM,0,2) and FST != '12'
-- [동적 조건] schDate         → AND TO_CHAR(DOMESTIC_STDATE,'yyyymmdd') <= ?
--             schDate         → AND TO_CHAR(DOMESTIC_EDDATE,'yyyymmdd') >= ?
--             schDeptCityCode → AND A.DOMESTIC_START_CITY = ?
--             schArrvCityCode → AND A.DOMESTIC_ARRIVAL_CITY = ?
--             schAirLine      → AND SUBSTR(DOMESTIC_NUM,0,2) = ?
--             schFlightNum    → AND DOMESTIC_NUM LIKE '%'||?||'%'
ORDER BY A.DOMESTIC_START_TIME ASC