SELECT
    A.INTERNATIONAL_IO_TYPE,
    A.INTERNATIONAL_NUM,
    A.INTERNATIONAL_TIME,
    A.INTERNATIONAL_MON,
    A.INTERNATIONAL_TUE,
    A.INTERNATIONAL_WED,
    A.INTERNATIONAL_THU,
    A.INTERNATIONAL_FRI,
    A.INTERNATIONAL_SAT,
    A.INTERNATIONAL_SUN,
    A.INTERNATIONAL_STDATE,
    A.INTERNATIONAL_EDDATE,
    B.AIRLINE_KOREAN,
    B.AIRLINE_ENGLISH,
    B.AIRLINE_HOMEPAGE_URL,
    A.INTERNATIONAL_AIRPORT_DOME as AIRPORT_CODE,
    (SELECT CITY_KOR FROM AIRPORT_CITY_CODE WHERE CITY_CODE = A.INTERNATIONAL_AIRPORT_DOME) as AIRPORT,
    A.INTERNATIONAL_AIRPORT_INTE as CITY_CODE,
    (SELECT CITY_KOR FROM AIRPORT_CITY_CODE WHERE CITY_CODE = A.INTERNATIONAL_AIRPORT_INTE) as CITY,
    CASE WHEN FST IN ('11', '13', '14', '15') THEN '여객기'
         WHEN FST IN ('21', '22', '23') THEN '화물기'
         ELSE '기타' END AS FLIGHT_PURPOSE
FROM
    AIRPORT_SCHEDULE_INTE A,
    AIRPORT_AIRLINE_CODE B
WHERE B.AIRLINE_CODE2=SUBSTR(A.INTERNATIONAL_NUM,0,2) AND INTERNATIONAL_TIME != 'null' AND FST != '12'
ORDER BY A.INTERNATIONAL_TIME ASC
