SELECT *
FROM 
(SELECT 
	TO_CHAR (A.DOMESTIC_STDATE, 'YYYYMMDD')||A.DOMESTIC_IDX AS fid,
	A.CRUD_TP_CD AS fgenType,
	to_char (A.DOMESTIC_REGDATE , 'YYYYMMDDHH24MISS') AS fgenTime,
    A.DOMESTIC_NUM AS flightId, 
    A.DOMESTIC_START_TIME AS st, 
    to_char(A.DOMESTIC_STDATE, 'YYYYMMDD') AS firstdate, 
    to_char(A.DOMESTIC_EDDATE, 'YYYYMMDD') AS lastdate, 
    A.DOMESTIC_MON AS ynMon, 
    A.DOMESTIC_TUE AS ynTue, 
    A.DOMESTIC_WED AS ynWed, 
    A.DOMESTIC_THU AS ynThu, 
    A.DOMESTIC_FRI AS ynFri, 
    A.DOMESTIC_SAT AS ynSat, 
    A.DOMESTIC_SUN AS ynSun, 
    B.AIRLINE_KOREAN AS airline,
    B.AIRLINE_CODE2 AS airlinecode, 
    A.DOMESTIC_START_CITY AS depCityCode,
    C.CITY_KOR AS depCity,
	A.DOMESTIC_ARRIVAL_CITY AS arrvCityCode,
	D.CITY_KOR AS arrvCity
FROM 
    AIRPORT_SCHEDULE_DOME_HIST A, 
    AIRPORT_AIRLINE_CODE B,
    AIRPORT_CITY_CODE C,
    AIRPORT_CITY_CODE D
WHERE B.AIRLINE_CODE2=SUBSTR(A.DOMESTIC_NUM,0,2) 
AND C.CITY_CODE = A.DOMESTIC_START_CITY
AND D.CITY_CODE = A.DOMESTIC_ARRIVAL_CITY
AND DOMESTIC_START_TIME != 'null' 
AND FST IN ('11', '13', '14', '15')
UNION ALL 
SELECT 
	TO_CHAR (A.DOMESTIC_STDATE, 'YYYYMMDD')||A.DOMESTIC_IDX AS fid,
	'I' AS fgenType,
	to_char (A.DOMESTIC_REGDATE , 'YYYYMMDDHH24MISS') AS fgenTime,
    A.DOMESTIC_NUM AS flightId, 
    A.DOMESTIC_START_TIME AS st, 
    to_char(A.DOMESTIC_STDATE, 'YYYYMMDD') AS firstdate, 
    to_char(A.DOMESTIC_EDDATE, 'YYYYMMDD') AS lastdate, 
    A.DOMESTIC_MON AS ynMon, 
    A.DOMESTIC_TUE AS ynTue, 
    A.DOMESTIC_WED AS ynWed, 
    A.DOMESTIC_THU AS ynThu, 
    A.DOMESTIC_FRI AS ynFri, 
    A.DOMESTIC_SAT AS ynSat, 
    A.DOMESTIC_SUN AS ynSun, 
    B.AIRLINE_KOREAN AS airline,
    B.AIRLINE_CODE2 AS airlinecode, 
    A.DOMESTIC_START_CITY AS depCityCode,
    C.CITY_KOR AS depCity,
	A.DOMESTIC_ARRIVAL_CITY AS arrvCityCode,
	D.CITY_KOR AS arrvCity
FROM 
    AIRPORT_SCHEDULE_DOME A, 
    AIRPORT_AIRLINE_CODE B,
    AIRPORT_CITY_CODE C,
    AIRPORT_CITY_CODE D
WHERE B.AIRLINE_CODE2=SUBSTR(A.DOMESTIC_NUM,0,2) 
AND C.CITY_CODE = A.DOMESTIC_START_CITY
AND D.CITY_CODE = A.DOMESTIC_ARRIVAL_CITY
AND DOMESTIC_START_TIME != 'null' 
AND FST IN ('11', '13', '14', '15')
AND to_char(A.DOMESTIC_STDATE, 'YYYYMMDD') <= SYSDATE
AND to_char(A.DOMESTIC_EDDATE, 'YYYYMMDD') >= SYSDATE)
WHERE 1=1
ORDER BY fgenTime desc