-- API: GET /flight/apron-status/pus
SELECT
    TO_CHAR (T1.ACT_DATE, 'YYYYMMDD')||T1.AIRPORT||T1.IO||T1.IATA||T1.FLN AS "ufid",
    CASE WHEN T1.IO = 'O' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT )
         WHEN T1.IO = 'I' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS "boardingKor",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS "boardingEng",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_CHN) CITY_CHN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_CHN) CITY_CHN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS "boardingChn",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_JPN) CITY_JPN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_JPN) CITY_JPN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS "boardingJpn",
    CASE WHEN T1.IO = 'O' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)
         WHEN T1.IO = 'I' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS "arrivedKor",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS "arrivedEng",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_CHN) CITY_CHN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_CHN) CITY_CHN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS "arrivedChn",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_JPN) CITY_JPN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_JPN) CITY_JPN FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS "arrivedJpn",
    T2.AIRLINE_KOREAN AS "airlineKorean",
    T2.AIRLINE_ENGLISH AS "airlineEnglish",
    T2.AIRLINE_CODE2||T1.FLN AS "airfln",
    TO_CHAR (T1.ACT_DATE, 'YYYYMMDD') AS "flightdate",
    T1.STD AS "std",
    T1.ETD AS "etd",
    T1.IO AS "io",
    CASE WHEN T1.LINE = 'D' THEN '국내' WHEN T1.LINE = 'I' THEN '국제' END AS "line",
    T1.LINE AS "lineCode",
    CASE WHEN T1.IO = 'I' THEN T1.GATE END AS "baggageClaim",
    CASE WHEN T1.IO = 'O' THEN T1.GATE END AS "gate",
    T3.RMK_KOR AS "rmkKor",
    T3.RMK_ENG AS "rmkEng",
    T3.RMK_CHN AS "rmkChn",
    T3.RMK_JPN AS "rmkJpn",
    T1.CITY AS "city",
    T1.AIRPORT AS "airport",
    T1.SPT_NM AS "sptNm"
FROM
    AIRPORT_FIDS_SCHEDULE T1 LEFT JOIN AIRPORT_AIRLINE_CODE T2 ON T1.ICAO = T2.AIRLINE_CODE3 AND T1.IATA = T2.AIRLINE_CODE2
    LEFT JOIN FIDS_STATUS T3 ON T1.RMK = T3.RMK_CODE
WHERE T1.FST IN ('11', '13', '15') AND T1.PPC IN ('00', '08') AND T1.DEL != 'Y'
-- [동적 조건] flightdate → AND TO_CHAR(T1.ACT_DATE,'yyyymmdd') = ?
--             airport    → AND T1.AIRPORT = ?
--             std        → AND T1.STD = ?
--             etd        → AND T1.ETD = ?
--             line       → AND T1.LINE = ?
--             io         → AND T1.IO = ?
--             airfln     → AND T2.AIRLINE_CODE2||T1.Fln LIKE UPPER('%'||?||'%')
