-- API: GET /flight/status/detail
-- View columns: BOARDING_KOR, BOARDING_ENG, ARRIVED_KOR, ARRIVED_ENG, AIRLINE_KOREAN, AIRLINE_ENGLISH,
--               AIR_FLN, FLIGHT_DATE, STD, ETD, IO, LINE_CODE, LINE, GATE, RMK_KOR, RMK_ENG,
--               CITY, AIRPORT, APL_REG_NO, ICAO_APM_CD
-- Model fields not in view: UFID(→NULL), BAGGAGE_CLAIM(→NULL)
SELECT
    NULL AS UFID,
    AIRLINE_KOREAN,
    AIRLINE_ENGLISH,
    AIRPORT,
    AIR_FLN,
    BOARDING_KOR,
    BOARDING_ENG,
    ARRIVED_KOR,
    ARRIVED_ENG,
    CITY,
    STD,
    ETD,
    FLIGHT_DATE,
    IO,
    LINE,
    LINE_CODE,
    GATE,
    NULL AS BAGGAGE_CLAIM,
    RMK_KOR,
    RMK_ENG
FROM VW_AIRPORT_FIDS_SCHEDULE
