SELECT
    T1.FID AS "fid",
    CASE WHEN T1.IO = 'O' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT )
         WHEN T1.IO = 'I' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS "boardingKor",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)  END AS "boardingEng",
    CASE WHEN T1.IO = 'O' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)
         WHEN T1.IO = 'I' THEN (SELECT CITY_KOR FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS "arrivedKor",
    CASE WHEN T1.IO = 'O' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.CITY)
         WHEN T1.IO = 'I' THEN (SELECT UPPER(CITY_ENG) CITY_ENG FROM AIRPORT_CITY_CODE CITYCODE WHERE CITYCODE.CITY_CODE = T1.AIRPORT)  END AS "arrivedEng",
    T2.AIRLINE_KOREAN AS "airlineKorean",
    T2.AIRLINE_ENGLISH AS "airlineEnglish",
    T1.CDSR_YN AS "cdsrYn",
    T2.AIRLINE_CODE2||T1.FLN AS "airFln",
    T1.ACT_C_DATE||T1.STD AS "std",
    T1.ACT_C_DATE||T1.ETD AS "etd",
    T1.IO AS "io",
    CASE WHEN T1.LINE = 'D' THEN '국내' WHEN T1.LINE = 'I' THEN '국제' END AS "line",
    T1.GATE AS "gate",
    T3.RMK_KOR AS "rmkKor",
    T3.RMK_ENG AS "rmkEng",
    T1.CITY AS "city",
    T1.AIRPORT AS "airport",
    T1.APL_REG_NO AS "aplRegNo",
    T1.ICAO_APM_CD AS "icaoApmCd"
FROM
    AIRPORT_FIDS_SCHEDULE T1 LEFT JOIN AIRPORT_AIRLINE_CODE T2 ON T1.ICAO = T2.AIRLINE_CODE3 AND T1.IATA = T2.AIRLINE_CODE2
    LEFT JOIN FIDS_STATUS T3 ON T1.RMK = T3.RMK_CODE
WHERE T1.FST IN ('11', '13', '15') AND T1.PPC IN ('00', '08') AND (T1.DEL != 'Y' OR (T1.DEL='Y' AND T1.RMK='SNL'))
-- [동적 조건] schAirCode          → AND T1.AIRPORT = ?
--             schStTime/schEdTime → AND T1.ACT_C_DATE||T1.STD BETWEEN ? AND ?
--             Line                → AND T1.LINE = UPPER(?)
--             schFln              → AND T2.AIRLINE_CODE2||T1.Fln LIKE UPPER('%'||?||'%')
--             schFID              → AND FID = ?
--             schAPLno            → AND APL_REG_NO= ?
--             schAPM              → AND T1.ICAO_APM_CD = ?
ORDER BY T1.STD ASC
