-- API: GET /flight/status/depart
WITH BASE_DATA AS (
    SELECT 
        T1.FID,
        TO_CHAR(CASE WHEN (T1.MARK='I' AND T1.DEL='N') THEN T1.ACT_DATE
                ELSE T1.MOD_DATE END, 'YYYYMMDDHH24MISS') AS FGENTIME,
        T1.ACT_C_DATE AS SEARCHDAY,
        T1.ACT_C_DATE||T1.STD AS SCHEDULEDATETIME,
        CASE WHEN T1.ETD IS NULL THEN T1.ACT_C_DATE||T1.STD 
             WHEN T1.ETD IS NOT NULL THEN T1.ACT_C_DATE||T1.ETD END AS ESTIMATEDDATETIME,
        T2.AIRLINE_KOREAN AS AIRLINE,
        T1.IO,
        T1.AIRPORT,
        T1.CITY,
        T1.CDSR_YN AS CODESHARE,
        T1.CDSR_MST_FL_NM AS MASTERFLIGHTID,
        T2.AIRLINE_CODE2||T1.FLN AS FLIGHTID,
        T3.RMK_KOR,
        CASE WHEN T1.LINE = 'D' THEN '국내' WHEN T1.LINE = 'I' THEN '국제' END AS LINE
    FROM 
        AIRPORT_FIDS_SCHEDULE T1 
        LEFT JOIN AIRPORT_AIRLINE_CODE T2 ON T1.ICAO = T2.AIRLINE_CODE3 AND T1.IATA = T2.AIRLINE_CODE2
        LEFT JOIN FIDS_STATUS T3 ON T1.RMK = T3.RMK_CODE
    WHERE 
        T1.FST IN ('11', '13', '15') 
        AND T1.PPC IN ('00', '08') 
        AND (T1.DEL != 'Y' OR (T1.DEL='Y' AND T1.RMK='SNL'))
        AND T1.ACT_C_DATE||T1.STD BETWEEN TO_CHAR(SYSDATE-3, 'YYYYMMDD') AND TO_CHAR(SYSDATE+7, 'YYYYMMDD')
        AND T1.IO = 'O' -- 출발
),
AIRPORT_INFO AS (
    SELECT 
        CITY_CODE,
        CITY_KOR,
        UPPER(CITY_ENG) AS CITY_ENG
    FROM 
        AIRPORT_CITY_CODE
),
FS AS (
    SELECT  
        B.FID,
        B.FGENTIME,
        B.SEARCHDAY,
        B.SCHEDULEDATETIME,
        B.ESTIMATEDDATETIME,
        B.AIRLINE,
        CASE WHEN B.IO = 'O' THEN DEP.CITY_KOR WHEN B.IO = 'I' THEN ARR.CITY_KOR END AS DEP_AIRPORT,
        CASE WHEN B.IO = 'O' THEN DEP.CITY_ENG WHEN B.IO = 'I' THEN ARR.CITY_ENG END AS DEP_AIRPORT_ENG,
        B.AIRPORT AS DEP_AIRPORT_CODE,
        CASE WHEN B.IO = 'O' THEN ARR.CITY_KOR WHEN B.IO = 'I' THEN DEP.CITY_KOR END AS ARR_AIRPORT,
        CASE WHEN B.IO = 'O' THEN ARR.CITY_ENG WHEN B.IO = 'I' THEN DEP.CITY_ENG END AS ARR_AIRPORT_ENG,
        B.CITY AS ARR_AIRPORT_CODE,
        B.CODESHARE,
        B.MASTERFLIGHTID,
        B.FLIGHTID,
        B.RMK_KOR,
        B.IO,
        B.LINE
    FROM 
        BASE_DATA B
        LEFT JOIN AIRPORT_INFO DEP ON B.AIRPORT = DEP.CITY_CODE
        LEFT JOIN AIRPORT_INFO ARR ON B.CITY = ARR.CITY_CODE
),
NEXT_DAY_INFO AS (
    SELECT 
        F1.FLIGHTID AS ORIG_FLIGHTID,
        F1.SEARCHDAY AS ORIG_SEARCHDAY,
        F2.ESTIMATEDDATETIME,
        F2.RMK_KOR
    FROM 
        FS F1
        JOIN FS F2 ON (F2.FLIGHTID = F1.FLIGHTID || 'A' OR F2.FLIGHTID = F1.FLIGHTID || 'D') 
                    AND TO_DATE(F2.SEARCHDAY,'YYYYMMDD') = TO_DATE(F1.SEARCHDAY,'YYYYMMDD')+1--TRUNC(F2.SEARCHDAY) = TRUNC(F1.SEARCHDAY) + 1
)
SELECT
    FS.FID AS "fid",
    FS.FGENTIME AS "fgenTime",
    FS.SEARCHDAY AS "searchday",
    FS.SCHEDULEDATETIME AS "scheduledatetime",
    COALESCE(ND.ESTIMATEDDATETIME, FS.ESTIMATEDDATETIME) AS "estimateddatetime",
    FS.AIRLINE AS "airline",
    FS.DEP_AIRPORT AS "depAirport",
    FS.DEP_AIRPORT_ENG AS "depAirportEng",
    FS.DEP_AIRPORT_CODE AS "depAirportCode",
    FS.ARR_AIRPORT AS "arrAirport",
    FS.ARR_AIRPORT_ENG AS "arrAirportEng",
    FS.ARR_AIRPORT_CODE AS "arrvAirportCode",
    FS.CODESHARE AS "codeshare",
    FS.MASTERFLIGHTID AS "masterflightid",
    FS.FLIGHTID AS "flightid",
    COALESCE(ND.RMK_KOR, FS.RMK_KOR) AS "rmkKor",
    FS.IO AS "io",
    FS.LINE AS "line"
FROM 
    FS
    LEFT JOIN NEXT_DAY_INFO ND ON FS.FLIGHTID = ND.ORIG_FLIGHTID AND FS.SEARCHDAY = ND.ORIG_SEARCHDAY
WHERE 1=1
-- [동적 조건] searchday       → AND searchday = ?
--             from_time       → AND SUBSTR(SCHEDULEDATETIME,9,4) >= ?
--             to_time         → AND SUBSTR(SCHEDULEDATETIME,9,4) <= ?
--             airport_code    → AND DEP_AIRPORT_CODE = UPPER(?)
--             airport         → AND DEP_AIRPORT LIKE '%'||?||'%'
--             arr_airport_code→ AND ARR_AIRPORT_CODE = UPPER(?)
--             arr_airport     → AND ARR_AIRPORT LIKE '%'||?||'%'
--             fgenTime        → AND fgenTime >= ?
--             f_id            → AND FID = ?
--             flight_id       → AND FLIGHTID = UPPER(?)
--             line            → AND (CASE WHEN LINE='국내' THEN 'D' WHEN LINE='국제' THEN 'I' ELSE LINE END = UPPER(?))
ORDER BY SEARCHDAY, SCHEDULEDATETIME ASC