-- API: GET /parking/realtime-status/info
SELECT A.PARKING_IINCNT                          AS "parkingIincnt",
       A.PARKING_IOUTCNT                          AS "parkingIoutcnt",
       A.PARKING_ISTAY                            AS "parkingIstay",
       TO_CHAR(A.PARKING_GETDATE, 'YYYY-MM-DD')   AS "parkingGetdate",
       TO_CHAR(A.PARKING_GETDATE, 'hh24:mi:ss')   AS "parkingGettime",
       A.PARKING_AIRPORT_CODE_NAME                AS "parkingAirportCodeName",
       A.PARKING_PULL_SPACE                        AS "parkingFullSpace",
       CASE WHEN A.PARKING_AIRPORT_CODE = 1 THEN '김포국제공항'
            WHEN A.PARKING_AIRPORT_CODE = 2 THEN '김해국제공항'
            WHEN A.PARKING_AIRPORT_CODE = 3 THEN '제주국제공항'
            WHEN A.PARKING_AIRPORT_CODE = 4 THEN '대구국제공항'
            WHEN A.PARKING_AIRPORT_CODE = 5 THEN '광주공항'
            WHEN A.PARKING_AIRPORT_CODE = 6 THEN '여수공항'
            WHEN A.PARKING_AIRPORT_CODE = 7 THEN '울산공항'
            WHEN A.PARKING_AIRPORT_CODE = 8 THEN '군산공항'
            WHEN A.PARKING_AIRPORT_CODE = 9 THEN '원주공항'
            WHEN A.PARKING_AIRPORT_CODE = 10 THEN '청주국제공항'
            WHEN A.PARKING_AIRPORT_CODE = 11 THEN '무안국제공항'
            WHEN A.PARKING_AIRPORT_CODE = 12 THEN '사천공항'
            WHEN A.PARKING_AIRPORT_CODE = 13 THEN '양양국제공항'
       END AS "aprKor",
       CASE WHEN A.PARKING_AIRPORT_CODE = 1 THEN 'GIMPO INTERNATIONAL AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 2 THEN 'GIMHAE INTERNATIONAL AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 3 THEN 'JEJU INTERNATIONAL AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 4 THEN 'DAEGU INTERNATIONAL AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 5 THEN 'GWANGJU AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 6 THEN 'YEOSU AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 7 THEN 'ULSAN AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 8 THEN 'GUNSAN AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 9 THEN 'WONJU AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 10 THEN 'CHEONGJU INTERNATIONAL AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 11 THEN 'MUAN INTERNATIONAL AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 12 THEN 'SACHEON AIRPORT'
            WHEN A.PARKING_AIRPORT_CODE = 13 THEN 'YANGYANG INTERNATIONAL AIRPORT'
       END AS "aprEng"
  FROM AIRPORT_PARKINGLIVE A
  WHERE 1=1
  
  
  
  
  
  
  
    
    
       
     
     
     
  AND TO_CHAR(A.PARKING_DTMGMNTDATE, 'yyyy-mm-dd') = TO_CHAR(SYSDATE, 'yyyy-mm-dd') --현재 유효한지 검증?
  ORDER BY A.PARKING_AIRPORT_CODE, A.PARKING_AIRPORT_CODE_NAME ASC